# Site settings
title: Hakumai - Mac用ニコ生コメントビューア(コメビュ)
tag_text: Hakumai is ???
description: HakumaiはMac OS Xに対応したニコニコ生放送用のコメントビューア(コメビュ)です。

# Build settings
markdown: kramdown

exclude: ["README.md"]

# Binary version
binary_version: 0.0.53
binary_date: 2021/5/9
