# Site settings
title: Hakumai - Mac用ニコ生コメントビューア(コメビュ)
tag_text: Hakumai
description: Hakumaiは Mac 用のニコニコ生放送用のコメントビューア(コメビュ)です。
canonical_url: https://honishi.github.io/Hakumai/

# Build settings
markdown: kramdown

exclude: ["README.md"]

# Binary version
binary_version: 3.8.2
binary_date: 2025/4/6
