name: Build and Run Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-12

    # checkout
    steps:
      - uses: actions/checkout@v2

      # debug prints
      - name: Show Xcode versions
        run: |
          xcodebuild -version
          ls /Applications | grep 'Xcode'

      # setup ruby and bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Check Ruby version
        run: ruby -v

      # setup xcode version
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      # setup xcode project
      - name: Setup cache for Pods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      - name: Pod install
        run: |
          # bundle exec pod repo update --silent
          bundle exec pod install

      # before test
      - name: Copy sample credential file
        run: cp ./Hakumai/OAuthCredential.sample.swift ./Hakumai/OAuthCredential.swift

      # build and run tests
      - name: Build and Run Tests
        run: |
          xcodebuild -version
          set -o pipefail && xcodebuild -workspace Hakumai.xcworkspace -scheme Hakumai -configuration Debug -destination 'platform=OS X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | bundle exec xcpretty -c
